# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/masters_project/binauralsensoryaugmentation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/masters_project/binauralsensoryaugmentation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/masters_project/binauralsensoryaugmentation/CMakeFiles /home/pi/masters_project/binauralsensoryaugmentation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/masters_project/binauralsensoryaugmentation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named binauralsensoryaugmentation

# Build rule for target.
binauralsensoryaugmentation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binauralsensoryaugmentation
.PHONY : binauralsensoryaugmentation

# fast build rule for target.
binauralsensoryaugmentation/fast:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/build
.PHONY : binauralsensoryaugmentation/fast

I2CDevice.o: I2CDevice.cpp.o

.PHONY : I2CDevice.o

# target to build an object file
I2CDevice.cpp.o:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/I2CDevice.cpp.o
.PHONY : I2CDevice.cpp.o

I2CDevice.i: I2CDevice.cpp.i

.PHONY : I2CDevice.i

# target to preprocess a source file
I2CDevice.cpp.i:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/I2CDevice.cpp.i
.PHONY : I2CDevice.cpp.i

I2CDevice.s: I2CDevice.cpp.s

.PHONY : I2CDevice.s

# target to generate assembly for a file
I2CDevice.cpp.s:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/I2CDevice.cpp.s
.PHONY : I2CDevice.cpp.s

LSM303AGR_MAG.o: LSM303AGR_MAG.cpp.o

.PHONY : LSM303AGR_MAG.o

# target to build an object file
LSM303AGR_MAG.cpp.o:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/LSM303AGR_MAG.cpp.o
.PHONY : LSM303AGR_MAG.cpp.o

LSM303AGR_MAG.i: LSM303AGR_MAG.cpp.i

.PHONY : LSM303AGR_MAG.i

# target to preprocess a source file
LSM303AGR_MAG.cpp.i:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/LSM303AGR_MAG.cpp.i
.PHONY : LSM303AGR_MAG.cpp.i

LSM303AGR_MAG.s: LSM303AGR_MAG.cpp.s

.PHONY : LSM303AGR_MAG.s

# target to generate assembly for a file
LSM303AGR_MAG.cpp.s:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/LSM303AGR_MAG.cpp.s
.PHONY : LSM303AGR_MAG.cpp.s

NMEAParser/Software/NMEAParserLib/NMEAParser.o: NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.o

.PHONY : NMEAParser/Software/NMEAParserLib/NMEAParser.o

# target to build an object file
NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.o:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.o
.PHONY : NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.o

NMEAParser/Software/NMEAParserLib/NMEAParser.i: NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.i

.PHONY : NMEAParser/Software/NMEAParserLib/NMEAParser.i

# target to preprocess a source file
NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.i:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.i
.PHONY : NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.i

NMEAParser/Software/NMEAParserLib/NMEAParser.s: NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.s

.PHONY : NMEAParser/Software/NMEAParserLib/NMEAParser.s

# target to generate assembly for a file
NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.s:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.s
.PHONY : NMEAParser/Software/NMEAParserLib/NMEAParser.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/binauralsensoryaugmentation.dir/build.make CMakeFiles/binauralsensoryaugmentation.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... binauralsensoryaugmentation"
	@echo "... edit_cache"
	@echo "... I2CDevice.o"
	@echo "... I2CDevice.i"
	@echo "... I2CDevice.s"
	@echo "... LSM303AGR_MAG.o"
	@echo "... LSM303AGR_MAG.i"
	@echo "... LSM303AGR_MAG.s"
	@echo "... NMEAParser/Software/NMEAParserLib/NMEAParser.o"
	@echo "... NMEAParser/Software/NMEAParserLib/NMEAParser.i"
	@echo "... NMEAParser/Software/NMEAParserLib/NMEAParser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

